### ISSUE TITLE
Windows: missing six module

### ISSUE THREAD

**Issue by Tomnl** [althonos/pronto#3]
- Missing module 'six' when pip install pronto 0.3.3
- Easy fix by installing six prior to pronto installation but would be best if we add six to the dependencies in the setup.py file

```


Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\tnl495>pip install mzml2isa
Collecting mzml2isa
  Downloading mzml2isa-0.4.25.tar.gz (128kB)
    100% |################################| 131kB 2.6MB/s
Collecting lxml (from mzml2isa)
  Downloading lxml-3.6.3.tar.gz (3.7MB)
    100% |################################| 3.7MB 145kB/s
Collecting pronto (from mzml2isa)
  Downloading pronto-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\tnl495\appdata\local\temp\pip-build-b_tcry\pronto\setup.py"
, line 9, in <module>
        import pronto
      File "pronto\__init__.py", line 14, in <module>
        from pronto.ontology import Ontology
      File "pronto\ontology.py", line 25, in <module>
        import six
    ImportError: No module named six

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\tnl495\a
ppdata\local\temp\pip-build-b_tcry\pronto
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\Users\tnl495>



```

**Comment by althonos** [comment]
How comes six is absent from the dependencies while being in the requirements.txt file ? Maybe I did something wrong when trying to assume the platform/implementation...

**Comment by pcm32** [comment]
I get this issue as well on a fresh ubuntu 16.04 installation with pip. Possibly something wrong with the requirements file as you suggest.

**Comment by althonos** [comment]
Should be fixed in 67085b8.

**Comment by Tomnl** [comment]
Hi Martin, 

I still get this problem when I try to install as part of mzml2isa on Windows. Has this update been added to pip?

**Comment by althonos** [comment]
Well, six is present in both requirements.txt and setup.py, but that may be
the first import that fails, so I'll add a try/except block in
pronto/__init__.py
